# Generated by Django 2.2 on 2019-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_kadzostagline_weekstheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='logos')),
            ],
        ),
    ]
