# Generated by Django 2.2 on 2019-04-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
