# Generated by Django 2.2 on 2019-04-05 09:13

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('content', martor.models.MartorField()),
            ],
        ),
    ]
