# Generated by Django 2.2 on 2019-04-10 07:20

import datetime
from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded', models.DateField(default=datetime.date.today)),
                ('updated', models.DateField(blank=True, null=True)),
                ('content', martor.models.MartorField()),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
