# Generated by Django 2.2 on 2019-04-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
